server:
  port: 8080
### datasource Configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ry?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456